GOOD_TYPES = (
    ('wood', 'Wood'),
    ('stone', 'Stone'),
    ('iron', 'Iron'),
    ('pitch', 'Pitch'),
    ('venison', 'Venison'),
    ('furniture', 'Furniture'),
    ('metalware', 'Metalware'),
    ('clothes', 'Clothes'),
    ('wine', 'Wine'),
    ('salt', 'Salt'),
    ('spices', 'Spices'),
    ('silk', 'Silk'),
    ('apples', 'Apples'),
    ('cheese', 'Cheese'),
    ('meat', 'Meat'),
    ('bread', 'Bread'),
    ('vegetables', 'Vegetables'),
    ('fish', 'Fish'),
    ('ale', 'Ale'),
    ('bows', 'Bows'),
    ('pikes', 'Pikes'),
    ('armour', 'Armour'),
    ('swords', 'Swords'),
    ('catapults', 'Catapults'),
)
